### ISSUE TITLE
build-rpc-images action might not be building PR branches

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#322]
The PR 315 image:

https://hub.docker.com/layers/bitcoindevproject/warnet-rpc/pr-315/images/sha256-eb24aaa9dd31d30ddef7d96d3375946f2a1e74fa230c10546a70572e3bcade45?context=explore

did not have the correct RPC code in the container when deployed on K8s, it looked like it was on main branch

**Comment by willcl-ark** [comment]
I think the issue is that https://github.com/bitcoin-dev-project/warnet/blob/93630d1956fea59960dfa95a247529a1f1a6ccbe/.github/workflows/build-rpc-images.yml#L14C15-L14C44 does auto-checkout of the repo using the [git context](https://github.com/docker/build-push-action?tab=readme-ov-file#git-context), but perhaps this is not actually checking out the branch, but only cloning?

**Comment by willcl-ark** [comment]
![image](https://github.com/bitcoin-dev-project/warnet/assets/6606587/b6a44edd-6b1a-435d-a790-c3c664220f45)

It seems to be here: https://github.com/bitcoin-dev-project/warnet/actions/runs/8454179209/job/23158601186#step:5:154

I found a [related issue](https://github.com/docker/build-push-action/issues/1083) too. Not sure why it's not working, I can check out that commit just fine locally...

I guess we can try the non-"git context" way
