### ISSUE TITLE
RPC passwords for multiplayer

### ISSUE THREAD

**Issue by mplsgrant** [bitcoin-dev-project/warnet#434]
Should we assign different RPC passwords to different nodes?

We need a multiplayer mode rather than being able to control all nodes on warnet.

**Comment by pinheadmz** [comment]
do we still need this or will namespaces take care of it

**Comment by josibake** [comment]
today with namespaces, we can set "warnet user" permissions so that they can only operate on pods in a set of namespaces. this means they have no visibility into what is going on in other namespaces. however, this doesn't stop them from figuring out some way to guess what another tanks host name might be and trying to connect to it via rpc using a default user name and password.

to me, defining team specific usernames and passwords makes sense, and with the new yaml config system seems like it would be trivial, I think? values.yaml will contain the default rpc password and username, and then we will override it in each teams namespace deployment.yaml
