### ISSUE TITLE
Persist bitcoin (and other) datadirs over pod restarts

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#448]

**Comment by josibake** [comment]
Needed for Tabconf?

**Comment by pinheadmz** [comment]
Since we are default `restart: false` now and no longer need a persistent rpc server inside the cluster, i do not think this is a tabconf priority. I think it will be more helpful for long running network simulations when nodes might restart "accidentally" and we would want them to restore state like a real production mainnet node

**Comment by willcl-ark** [comment]
I agree and thisnk we can close for now to keep issues more focussed.
