### ISSUE TITLE
quickstart: add podman as backend option for k8s

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#569]
> (I would prefer to run podman if possible over docker to avoid the root access).

**Comment by pinheadmz** [comment]
closing as "won't fix" after offline discussion, we'll stick to minikube and docker (with rootless mode available)

**Comment by josibake** [comment]
I'd say this is more a case of "we only officially support docker as a backend for minikube." You can run minikube with Podman as the driver: https://minikube.sigs.k8s.io/docs/drivers/podman/

So a user can run minikube however they want and warnet should *just work* (tm) since our interface is minikube/kubectl. That being said, if people run into weird edge cases trying to use minikube with a different driver (highly doubt they will), then our response would be "soz, we only support the docker driver for minikube."
