### ISSUE TITLE
scenario cli_help isn't available anymore

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#571]
since we removed `scenarios list` the help messages that describe scenarios are not available to user anywhere

**Comment by josibake** [comment]
it is, directly from the scenarios themselves, i.e., `./scenarios/mining_std.py --help`

**Comment by pinheadmz** [comment]
> it is, directly from the scenarios themselves, i.e., `./scenarios/mining_std.py --help`

That returns the argument options but not the scenario description

**Comment by josibake** [comment]
good point, I think we need to move all of those scenario descriptions down into the `parse_args` section of the scenario, vs having it in its own function. This is also nice because the help is self updating and always in line with the current arguments for the scenario, whereas before we were hardcoding the help text.
